---
title: "Patentsview Data - 2022 Table Contest Entry"
author: "Russ Allen and Chris Baker"
date: '2022-10-27'
output:
  knitr:::html_vignette:
    number_sections: yes
    toc: yes
vignette: |
  %\VignetteIndexEntry{Top assignees}
  %\VignetteEngine{knitr::rmarkdown_notangle}
---

<style type="text/css">
table, table th, table td {
  border: none;
}
</style>



```r
library(patentsview)
library(dplyr)
```

```
## 
## Attaching package: 'dplyr'
```

```
## The following objects are masked from 'package:stats':
## 
##     filter, lag
```

```
## The following objects are masked from 'package:base':
## 
##     intersect, setdiff, setequal, union
```

```r
library(highcharter)
```

```
## Registered S3 method overwritten by 'quantmod':
##   method            from
##   as.zoo.data.frame zoo
```

```r
library(DT)
library(knitr)

# With the recent API change that limits the overall result set size, we now look
# for databases (plural) where we used to use the singular database for this vignette.
# We also exclude patents without an assignee organization.

# We first need to write a query. Our query will look for "databases" in either 
# the patent title or abstract...Note, this isn't a terribly good way to ID our 
# patents, but it will work for the purpose of demonstration. Users who are 
# interested in writing higher-quality queries could consult the large body of 
# research that has been done in field of patent document retrieval.
query <- with_qfuns(
  and(
     neq("assignees_at_grant.organization" = ""),
     or(
       text_phrase(patent_abstract = "databases"),
       contains(patent_title = "databases")
     )
   )
)

query
```

```
## {"_and":[{"_neq":{"assignees_at_grant.organization":""}},{"_or":[{"_text_phrase":{"patent_abstract":"databases"}},{"_contains":{"patent_title":"databases"}}]}]}
```

```r
#> {"_and":[{"_neq":{"assignees_at_grant.organization":""}},{"_or":[{"_text_phrase":{"patent_abstract":"databases"}},{"_contains":{"patent_title":"databases"}}]}]}

# Create a list of the fields we'll need for the analysis

fields <- c(
  "patent_number", "patent_date","patent_year",
  "patent_num_us_patents_cited",
  "assignees_at_grant.organization",  # fulltext field now if used in q:
  "assignees_at_grant.assignee_id"  # the assignee fields come back in a nested object
)

# Send an HTTP request to the PatentsView API to get the data
pv_out <- search_pv(query, fields = fields, all_pages = TRUE, per_page = 1000)

knitr::opts_chunk$set(
   delay = 30
)

# Unnest the data frames that are stored in the assignee list column
dl <- unnest_pv_data(pv_out$data, "patent_number")
dl
```

```
## List of 2
##  $ assignees_at_grant:'data.frame':	7150 obs. of  3 variables:
##   ..$ patent_number: chr [1:7150] "4751635" ...
##   ..$ assignee     : chr [1:7150] "https://search.patentsview.org/api/v1/assi"..
##   ..$ organization : chr [1:7150] "Bell Communications Research, Inc." ...
##  $ patents           :'data.frame':	7598 obs. of  4 variables:
##   ..$ patent_number              : chr [1:7598] "4751635" ...
##   ..$ patent_date                : chr [1:7598] "1988-06-14" ...
##   ..$ patent_year                : int [1:7598] 1988 1988 ...
##   ..$ patent_num_us_patents_cited: int [1:7598] 3 18 ...
```

```r
#> List of 2
#>  $ assignees_at_grant:'data.frame':  7150 obs. of  3 variables:
#>   ..$ patent_number: chr [1:7150] "4751635" ...
#>   ..$ assignee     : chr [1:7150] "https://search.patentsview.org/api/v1/assi"..
#>   ..$ organization : chr [1:7150] "Bell Communications Research, Inc." ...
#>  $ patents           :'data.frame':  7598 obs. of  4 variables:
#>   ..$ patent_number              : chr [1:7598] "4751635" ...
#>   ..$ patent_date                : chr [1:7598] "1988-06-14" ...
#>   ..$ patent_year                : int [1:7598] 1988 1988 ...
#>   ..$ patent_num_us_patents_cited: int [1:7598] 3 18 ...

# We shouldn't need the filter (we queried for non empty string orginazations) but
# some are NA somehow

# We don't get the assignee_total_num_patents back from the patents endpoint any longer.
# We'll have to make a call to the assignee endpoint once we know who the top 75
# assignees are.

# Requested assignees_at_grant.assignee_id comes back in the assignees_at_grant object 
# with key "assignee" and value like https://search.patentsview.org/api/v1/assignee/35/
# We want to parse out the assignee_ids (35 in the example value)

# Create a data frame with the top 75 assignees:
top_asgns <-
  dl$assignees_at_grant %>%
    filter(!is.na(organization)) %>% # some patents are assigned to an inventor (not an org)
    mutate(assignee_id = gsub(".*/([0-9]+)/$", "\\1", assignee)) %>%
    group_by(organization, assignee_id) %>% 
    summarise(db_pats = n()) %>% 
    ungroup() %>%
    arrange(desc(db_pats)) %>%
    slice(1:75)
```

```
## `summarise()` has grouped output by 'organization'. You can override
## using the `.groups` argument.
```

```r
# Now that we have the assignee_id's we can call the assignee endpoint to get the
# total number of patents for each of our top_asgns 

assignee_query =  qry_funs$eq(assignee_id = as.integer(top_asgns$assignee_id))

assignee_fields <- c(
  "assignee_id","organization", "num_patents" 
)

# we'll post to the API, the query is a pretty large string (an "or" of 75 assignee_ids)
assignee_out <- search_pv(assignee_query , fields = assignee_fields, all_pages = TRUE, 
   per_page = 1000, endpoint = "assignees", method = "POST")

assignee_counts <- unnest_pv_data(assignee_out$data, "assignee_id")
assignee_counts
```

```
## List of 1
##  $ assignees:'data.frame':	75 obs. of  3 variables:
##   ..$ assignee_id : int [1:75] 3 6 ...
##   ..$ organization: chr [1:75] "Xerox Corporation" ...
##   ..$ num_patents : int [1:75] 23495 80931 ...
```

```r
#> List of 1
#>  $ assignees:'data.frame':   75 obs. of  3 variables:
#>   ..$ assignee_id : int [1:75] 3 6 ...
#>   ..$ organization: chr [1:75] "Xerox Corporation" ...
#>   ..$ num_patents : int [1:75] 23495 80931 ...

# Here we redo top_asgns now that we have all the fields we need.
# We join in the total counts and mutate in the percentages 
top_asgns <- dl$assignees_at_grant %>%
   inner_join(assignee_counts$assignees) %>%
   rename(ttl_pats = num_patents) %>%
   group_by(organization, ttl_pats) %>%
   summarise(db_pats = n()) %>% 
   mutate(frac_db_pats = round(db_pats / ttl_pats, 3)) %>%
   select(c(1, 3, 2, 4))  %>%
   arrange(desc(db_pats))
```

```
## Joining, by = "organization"
```

```
## `summarise()` has grouped output by 'organization'. You can override
## using the `.groups` argument.
```

```r
# Create datatable
datatable(
  data = top_asgns,
  rownames = FALSE,
  colnames = c(
    "Assignee", "DB patents","Total patents", "DB patents / total patents"
  ),
  caption = htmltools::tags$caption(
    style = 'caption-side: top; text-align: left; font-style: italic;',
    "Table 1: Top assignees in 'databases'"
  ),
  options = list(pageLength = 10)
)
```

<div class="figure">
<!--html_preserve--><div id="htmlwidget-d59f247f127bcb4062d9" style="width:100%;height:auto;" class="datatables html-widget"></div>
<script type="application/json" data-for="htmlwidget-d59f247f127bcb4062d9">{"x":{"filter":"none","vertical":false,"caption":"<caption style=\"caption-side: top; text-align: left; font-style: italic;\">Table 1: Top assignees in 'databases'<\/caption>","data":[["INTERNATIONAL BUSINESS MACHINES CORPORATION","Microsoft Technology Licensing, LLC","Oracle International Corporation","AT&amp;T Intellectual Property I, L.P.","SAP SE","EMC IP Holding Company LLC","Amazon Technologies, Inc.","LUCENT MEDICAL SYSTEMS, INC.","AS America, Inc.","CISCO TECHNOLOGY, INC.","AT&amp;T Technologies Incorporated","Hitachi, Ltd.","salesforce.com, inc.","SAP AG","Google LLC","Hewlett-Packard Development Company, L.P.","FUJITSU LIMITED","Palantir Technologies Inc.","Apple Inc.","Telefonaktiebolaget LM Ericsson (Publ)","Island Intellectual Property, LLC","BMC Software, Inc.","IN&amp;MOTION","ACCENTURE GLOBAL SOLUTIONS LIMITED","SIEMENS AKTIENGESELLSCHAFT","Delphix Corporation","Allstate Insurance Company","YAHOO HOLDINGS, INC.","General Electric Company","SYBASE, INC.","Xerox Corporation","SONY CORPORATION","JPMORGAN CHASE BANK, N.A.","Dell Products L.P.","Intel Corporation","ServiceNow, Inc.","Sun Microsystems Inc.","i2 Technologies US, Inc.","Red Hat, Inc.","NCR Corporation","Nortel Networks S.A.","Sprint Communications Company L.P.","Teradata US, Inc.","The Board of Trustees of the Leland Stanford Junior University","NEC CORPORATION","Nokia Technologies Oy","THE REGENTS OF THE UNIVERSITY OF CALIFORNIA","AMERICAN EXPRESS TRAVEL RELATED SERVICES COMPANY, INC.","MASSACHUSETTS MUTUAL LIFE INSURANCE COMPANY","Ricoh Company, Ltd.","Symantec Corporation","THE BOEING COMPANY","Alcatel Lucent","CAREFUSION 303, INC.","Koninklijke Philips N.V.","ORACLE AMERICA, INC.","PalmSource Inc.","Pivotal Software, Inc.","Unisys Corporation","Bell Atlantic Network Services","Facebook, Inc.","Honeywell International Inc.","Kayak Software Corporation","MongoDB, Inc.","UNITED SERVICES AUTOMOBILE ASSOCIATION (USAA)","UNIVERSITY OF TENNESSEE RESEARCH FOUNDATION","3Com Corporation","Canon Kabushiki Kaisha","Kabushiki Kaisha Toshiba","Motorola Solutions, Inc.","Oracle Systems Corporation","REDKNEE INC.","CADENCE DESIGN SYSTEMS, INC.","Capital One Services, LLC","Ciena Corporation"],[743,321,166,93,91,73,68,55,54,53,52,49,45,45,44,43,41,40,36,34,32,27,27,26,26,25,24,24,23,23,23,22,21,20,20,20,20,19,19,18,18,18,18,18,17,17,17,16,16,15,15,15,14,14,14,14,14,14,14,13,13,13,13,13,13,13,12,12,12,12,12,12,11,11,11],[150818,47743,8336,16621,3844,9796,15802,9434,4320,16856,4755,43825,2627,3648,24831,37773,39228,899,26445,19732,70,395,4509,2272,31086,35,652,2464,49684,344,23495,57152,1083,6891,46429,551,7630,198,2439,4284,4161,3700,511,4226,32150,11863,13175,1156,212,26504,3069,18957,6284,491,18383,1921,153,186,2431,306,6849,13469,26,52,1657,2624,1516,80931,53683,22101,470,61,2248,2278,1499],[0.005,0.007,0.02,0.006,0.024,0.007,0.004,0.006,0.013,0.003,0.011,0.001,0.017,0.012,0.002,0.001,0.001,0.044,0.001,0.002,0.457,0.068,0.006,0.011,0.001,0.714,0.037,0.01,0,0.067,0.001,0,0.019,0.003,0,0.036,0.003,0.096,0.008,0.004,0.004,0.005,0.035,0.004,0.001,0.001,0.001,0.014,0.075,0.001,0.005,0.001,0.002,0.029,0.001,0.007,0.092,0.075,0.006,0.042,0.002,0.001,0.5,0.25,0.008,0.005,0.008,0,0,0.001,0.026,0.197,0.005,0.005,0.007]],"container":"<table class=\"display\">\n  <thead>\n    <tr>\n      <th>Assignee<\/th>\n      <th>DB patents<\/th>\n      <th>Total patents<\/th>\n      <th>DB patents / total patents<\/th>\n    <\/tr>\n  <\/thead>\n<\/table>","options":{"pageLength":10,"columnDefs":[{"className":"dt-right","targets":[1,2,3]}],"order":[],"autoWidth":false,"orderClasses":false}},"evals":[],"jsHooks":[]}</script><!--/html_preserve-->
<p class="caption">plot of chunk unnamed-chunk-1</p>
</div>
